name: Release Style Kit

on:
  push:
    tags:
      - 'releases/style-kit/**'
      - '!releases/style-kit/**-beta*'

jobs:
  create_style_kit_release:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm install
      - run: npm test
        env:
          CI: true
      - run: npx lerna run build --scope @meeco/style-kit
      - name: Publish NPM
        run: |
          npx lerna exec --scope @meeco/style-kit -- npm config set //registry.npmjs.org/:_authToken=$NODE_AUTH_TOKEN
          npx lerna exec --scope @meeco/style-kit -- npm config set scope "@meeco"
          npx lerna exec --scope @meeco/style-kit -- npm publish --access public
        env:
          CI: true
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}
      - run: npm run docs
      - name: Deploy SDK docs to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.SDK_DOCS_DEPLOY_KEY }}
          publish_dir: ./docs/style-kit
          destination_dir: style-kit
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          external_repository: Meeco/sdk-docs
          publish_branch: master
